{{/* SPDX-FileCopyrightText: 2025 Deutsche Telekom AG

 SPDX-License-Identifier: Apache-2.0*/}}
{{- range $realmName, $realm := .Values.realm }}
{{- with $ }}
{{- if $realm.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "iris.fullname" . }}-{{ $realmName }}
  labels:
    {{- include "iris.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "iris.fullname" . }}-{{ $realmName }}
  minReplicas: {{ $realm.autoscaling.minReplicas }}
  maxReplicas: {{ $realm.autoscaling.maxReplicas }}
  metrics:
  {{- if $realm.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $realm.autoscaling.targetMemoryUtilizationPercentage }}
  {{- else if $realm.autoscaling.targetMemoryAverageValue }}
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: {{ $realm.autoscaling.targetMemoryAverageValue }}
  {{- end }}
  {{- if $realm.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $realm.autoscaling.targetCPUUtilizationPercentage }}
  {{- else if $realm.autoscaling.targetCPUAverageValue }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: {{ $realm.autoscaling.targetCPUAverageValue }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
