{{/* SPDX-FileCopyrightText: 2025 Deutsche Telekom AG

 SPDX-License-Identifier: Apache-2.0*/}}
{{- if .Values.component.sidecar.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-admin
  namespace: {{ .Release.Namespace }}
  labels: {{- include "iris.labels" . | nindent 4 }}
type: Opaque
data:
  HYDRA_ADMIN_USERNAME: {{ .Values.component.sidecar.config.basicAuthUsername | b64enc }}
  HYDRA_ADMIN_PASSWORD: {{ .Values.component.sidecar.config.basicAuthPassword | b64enc }}
{{- end }}