{{/* SPDX-FileCopyrightText: 2025 Deutsche Telekom AG

 SPDX-License-Identifier: Apache-2.0*/}}
{{- if .Values.service.admin.enabled }}
{{- range $realmName, $realm := .Values.realm }}
{{- with $ }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "iris.fullname" . }}-admin-{{ $realmName }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "iris.labels" . | indent 4 }}
    {{- with .Values.service.admin.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.admin.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.admin.type }}
  ports:
    {{- if .Values.service.admin.isDirectAccess }}
    - port: {{ .Values.service.admin.port }}
      targetPort: http-admin
      protocol: TCP
      name: {{ .Values.service.admin.name }}
    {{- else }}
    - port: {{ .Values.service.admin.port }}
      targetPort: http-sidecar
      protocol: TCP
      name: {{ .Values.service.sidecar.name }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "iris.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    iris.realm: {{ $realmName }}
{{- end }}
---
{{- end }}
{{- end }}
