{{/* SPDX-FileCopyrightText: 2025 Deutsche Telekom AG

 SPDX-License-Identifier: Apache-2.0*/}}
{{- if .Values.service.public.enabled }}
{{- range $realmName, $realm := .Values.realm }}
{{- with $ }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "iris.fullname" . }}-public-{{ $realmName }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "iris.labels" . | indent 4 }}
    {{- with .Values.service.public.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.public.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.public.type }}
  ports:
    - port: {{ .Values.service.public.port }}
      name: {{ .Values.service.public.name }}-hydra
      protocol: TCP
      targetPort: http-public
  selector:
    app.kubernetes.io/name: {{ include "iris.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    iris.realm: {{ $realmName }}
{{- end }}
---
{{- end }}
{{- end }}